[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico
framework = arduino
board_build.core = earlephilhower

; PacketSerial library
lib_deps = 
    bakercp/PacketSerial@^1.4.0

; Upload via UF2
upload_protocol = mbed
